"""Versioned, framework-independent InnexQ domain contracts."""

from innexq_contracts.hashing import (
    ApprovalBindingError,
    approval_matches_current_version,
    canonical_json_bytes,
    compute_brief_hash,
    version_brief,
)
from innexq_contracts.models import (
    Action,
    ActionManifest,
    ActionType,
    ActorContext,
    Alternative,
    ApprovalDecision,
    AuthorityResult,
    AuthorityVerdict,
    CalculationRecord,
    Classification,
    Decision,
    DecisionBrief,
    EvidenceGap,
    EvidenceGapKind,
    EvidenceItem,
    MaterialClaim,
    PolicyCheck,
    PolicyVerdict,
    Presentation,
    Recommendation,
    Run,
    RunState,
    SourceKind,
    VersionedBrief,
)
from innexq_contracts.transitions import (
    InvalidTransition,
    allowed_targets,
    assert_transition,
    can_transition,
)

__all__ = [
    "Action",
    "ActionManifest",
    "ActionType",
    "ActorContext",
    "Alternative",
    "ApprovalBindingError",
    "ApprovalDecision",
    "AuthorityResult",
    "AuthorityVerdict",
    "CalculationRecord",
    "Classification",
    "Decision",
    "DecisionBrief",
    "EvidenceGap",
    "EvidenceGapKind",
    "EvidenceItem",
    "InvalidTransition",
    "MaterialClaim",
    "PolicyCheck",
    "PolicyVerdict",
    "Presentation",
    "Recommendation",
    "Run",
    "RunState",
    "SourceKind",
    "VersionedBrief",
    "allowed_targets",
    "approval_matches_current_version",
    "assert_transition",
    "can_transition",
    "canonical_json_bytes",
    "compute_brief_hash",
    "version_brief",
]
